* LabHelper
Tool for assisting in Lab instruction. Allows instructor to send commands to user's computer for alert and lock, and automatically uploads user files while being worked on to allow instructor to monitor progress in near real-time.

The client is configured to assume that the client will be using bluej (http://bluej.org), as that is the software used for the course this tool was designed for. This can be easily changed in code.

Note that in its current state, this is fairly minimal and does what I need it to do. I welcome improvements.

** Features
- Uploads client computer's project to server for easy browsing
- Remotely send alert messages and urls via admin.py script in server
- Save attendance list to disk from admin
- Remotely lock and unlock client computers
- Serve pre-configured packages to clients that can be easily downloaded and worked on.


* Server
The server is written in Python 2.7+ and depends on Twisted (not included)

** Configuration
Stored in settings.json. Re-read at each access, so can be changed while server is running
- =activity= - Name of currently running lab activity
- =path= - Path to save uploaded files
- =activityfile= - Zip file containing current BlueJ activity. Project files should be in root
- =adminpassword= - Password required by admin.py
- =rosterfile= - output file for roster
- =port= - Port to run on

* Client
The client is written in Java and depends on the jars in the deps/ folder being in the classpath.

** Configuration
Config is generated at runtime. You need to change CSTRLOC in Uploader.java to points to a text file of the format: 
=IP=
=PORT=
where IP and PORT are the hostname and port of the server.

Recompile and distribute the JAR file.

* Author Information
Greg Cordts
greg -at- gregcor.com
http://gregcor.com


* License
** Bundled Dependencies
- Apache Codec is distributed under Apache 2.0 License (http://commons.apache.org/codec/license.html)
- json-simple is under the Apache 2.0 License (http://code.google.com/p/json-simple/)
** Project License
This software is licensed under the *MIT License*.

Copyright (C) 2011 by Greg Cordts

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

